language: python
python:
  - "3.5"

install:
  - pip3 install -r requirements.txt

script:
  - py.test --cov-config tests/.coveragerc -v --cov=deniable --cov-report=term --cov-report=html

after_success:
  - coveralls